/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tunglv.sqlite.ui;

import com.tunglv.sqlite.ui.customer.CustomerSearch;
import com.tunglv.sqlite.ui.mail.MailSearchAndAddNew;
import com.tunglv.sqlite.ui.user.UserSearch;

/**
 *
 * @author TUNGLV
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btUserSystem = new javax.swing.JButton();
        btCustomerManage = new javax.swing.JButton();
        btEmailManage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DashBoard");

        btUserSystem.setText("Quản lý người dùng");
        btUserSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUserSystemActionPerformed(evt);
            }
        });

        btCustomerManage.setText("Quản lý khách hàng");
        btCustomerManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCustomerManageActionPerformed(evt);
            }
        });

        btEmailManage.setText("Quản lý Email");
        btEmailManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEmailManageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btUserSystem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCustomerManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66)
                .addComponent(btEmailManage, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btEmailManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btUserSystem, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addComponent(btCustomerManage, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btUserSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUserSystemActionPerformed
        this.dispose();
        new UserSearch();
    }//GEN-LAST:event_btUserSystemActionPerformed

    private void btCustomerManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCustomerManageActionPerformed
        this.dispose();
        new CustomerSearch();
    }//GEN-LAST:event_btCustomerManageActionPerformed

    private void btEmailManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEmailManageActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MailSearchAndAddNew();
    }//GEN-LAST:event_btEmailManageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCustomerManage;
    private javax.swing.JButton btEmailManage;
    private javax.swing.JButton btUserSystem;
    // End of variables declaration//GEN-END:variables
}
